apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudflare-ddns-update.fullname" . }}
  labels:
    {{- include "cloudflare-ddns-update.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cloudflare-ddns-update.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cloudflare-ddns-update.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cloudflare-ddns-update.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          env:
            - name: CLOUDFLARE_ZONE
              value: {{ .Values.configuration.cloudflare.zone | quote }}
            {{- if ne .Values.configuration.cloudflare.apiToken "" }}
            - name: CLOUDFLARE_API_TOKEN
              value: {{ .Values.configuration.cloudflare.apiToken | quote }}
            {{- else if .Values.configuration.cloudflare.apiTokenExistingSecret }}
            - name: CLOUDFLARE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.configuration.cloudflare.apiTokenExistingSecret.tokenKey }}
                  name: {{ .Values.configuration.cloudflare.apiTokenExistingSecret.name }}
            {{- end }}
            {{- if ne .Values.configuration.auth.username "" }}
            - name: AUTH_USERNAME
              value: {{ .Values.configuration.auth.username | quote }}
            {{- else if .Values.configuration.auth.existingSecret }}
            - name: AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.configuration.auth.existingSecret.usernameKey }}
                  name: {{ .Values.configuration.auth.existingSecret.name }}
            {{- end }}
            {{- if ne .Values.configuration.auth.password "" }}
            - name: AUTH_PASSWORD
              value: {{ .Values.configuration.auth.password | quote }}
            {{- else if .Values.configuration.auth.existingSecret }}
            - name: AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.configuration.auth.existingSecret.passwordKey }}
                  name: {{ .Values.configuration.auth.existingSecret.name }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
